sm8350-common: sepolicy: Label extcon sysfs node for qti battery manager
 * Needed after https://github.com/LineageOS/android_device_qcom_sepolicy_vndr/commit/04b5abe092b445ebbf664174dde0e736464dc5dc

 * For warnings like:
04-11 23:44:53.115  2096  2132 W ExtconUEventObserver: Caused by:
android.system.ErrnoException: open failed: EACCES (Permission denied)
04-11 23:44:53.115  2096  2132 W ExtconUEventObserver: 	at
libcore.io.Linux.open(Native Method)
04-11 23:44:53.115  2096  2132 W ExtconUEventObserver: 	at
libcore.io.ForwardingOs.open(ForwardingOs.java:563)
04-11 23:44:53.115  2096  2132 W ExtconUEventObserver: 	at
libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
04-11 23:44:53.115  2096  2132 W ExtconUEventObserver: 	at
libcore.io.IoBridge.open(IoBridge.java:560)
04-11 23:44:53.115  2096  2132 W ExtconUEventObserver: 	... 17 more
04-11 23:44:53.115  2096  2096 W android.ui: type=1400 audit(0.0:43):
avc: denied { read } for name="name" dev="sysfs" ino=111869
scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass=file
permissive=0
04-11 23:44:53.115  2096  2096 W android.ui: type=1400 audit(0.0:44):
avc: denied { read } for name="name" dev="sysfs" ino=111866
scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass=file
permissive=0
04-11 23:44:53.115  2096  2096 W android.ui: type=1400 audit(0.0:45):
avc: denied { read } for name="name" dev="sysfs" ino=52757
scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass=file
permissive=0
04-11 23:44:53.117  2096  2132 W ExtconUEventObserver: Unable to read
/sys/devices/platform/soc/soc:qcom,pmic_glink/soc:qcom,pmic_glink:qcom,battery_charger/extcon/extcon3/cable.1/name.
This probably means the selinux policies need to be changed.

Signed-off-by: EndCredits <endcredits@crepuscular-aosp.icu>