sm8350-common: sepolicy: Address more denial
sm7325-common: sepolicy: Grant perms to mount tracefs when CONFIG_DEBUG_FS

avc:  denied  { mounton } for  pid=1 comm="init" path="/sys/kernel/tracing"
dev="tracefs" ino=1 scontext=u:r:init:s0 tcontext=u:object_r:debugfs_tracing_debug:s0 tclass=dir permissive=0

Change-Id: Ia71539ff4b622d5130f2051e8ae490f3b7a4722b

sm7325-common: Allow vendor init to geattr cgroups

W init: type=1400 audit(0.0:6): avc: denied { getattr } for path="/dev/cpuctl/tasks" dev="cgroup" ino=5 scontext=u:r:vendor_init:s0 tcontext=u:object_r:cgroup:s0 tclass=file permissive=0
Change-Id: Id319dcb7396b4794ca5c454b875a28e8e10c8faf

sm7325-common: Resolve a kernel selinux denial

W kworker/u16: 4: type=1400 audit(0.0:4): avc: denied { sys_admin } for capability=21 scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=capability permissive=0
Change-Id: I7fa44418137e3bc076f9e569c37fa0605764dbc8

sm7325-common: sepolicy: allow mkswap to kill

` mkswap  : type=1400 audit(0.0:18): avc: denied { kill } for capability=5 scontext=u:r:toolbox:s0 tcontext=u:r:toolbox:s0 tclass=capability permissive=0`

Signed-off-by: Pulkit077 <pulkitagarwal2k1@gmail.com>

sm7325-common: Label extcon sysfs node for qti battery manager

* Needed after https://github.com/LineageOS/android_device_qcom_sepolicy_vndr/commit/04b5abe092b445ebbf664174dde0e736464dc5dc

 * For warnings like:
04-11 23:44:53.115  2096  2132 W ExtconUEventObserver: Caused by:
android.system.ErrnoException: open failed: EACCES (Permission denied)
04-11 23:44:53.115  2096  2132 W ExtconUEventObserver: 	at
libcore.io.Linux.open(Native Method)
04-11 23:44:53.115  2096  2132 W ExtconUEventObserver: 	at
libcore.io.ForwardingOs.open(ForwardingOs.java:563)
04-11 23:44:53.115  2096  2132 W ExtconUEventObserver: 	at
libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
04-11 23:44:53.115  2096  2132 W ExtconUEventObserver: 	at
libcore.io.IoBridge.open(IoBridge.java:560)
04-11 23:44:53.115  2096  2132 W ExtconUEventObserver: 	... 17 more
04-11 23:44:53.115  2096  2096 W android.ui: type=1400 audit(0.0:43):
avc: denied { read } for name="name" dev="sysfs" ino=111869
scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass=file
permissive=0
04-11 23:44:53.115  2096  2096 W android.ui: type=1400 audit(0.0:44):
avc: denied { read } for name="name" dev="sysfs" ino=111866
scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass=file
permissive=0
04-11 23:44:53.115  2096  2096 W android.ui: type=1400 audit(0.0:45):
avc: denied { read } for name="name" dev="sysfs" ino=52757
scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass=file
permissive=0
04-11 23:44:53.117  2096  2132 W ExtconUEventObserver: Unable to read
/sys/devices/platform/soc/soc:qcom,pmic_glink/soc:qcom,pmic_glink:qcom,battery_charger/extcon/extcon3/cable.1/name.
This probably means the selinux policies need to be changed.

Signed-off-by: EndCredits <endcredits@crepuscular-aosp.icu>

sm7325-common: sepolicy: Address vdc denial

03-09 18:57:26.091  4516  4516 W vdc     : type=1400 audit(0.0:24): avc: denied { kill } for capability=5 scontext=u:r:vdc:s0 tcontext=u:r:vdc:s0 tclass=capability permissive=0

Change-Id: I4f4cd6dd342c862015bfd39b9b67b606193ffc8c
Signed-off-by: iusmac <iusico.maxim@libero.it>

sm7325-common: sepolicy: Address cameraserver denial

avc: denied { write } for name="property_service" dev="tmpfs" ino=16815 scontext=u:r:cameraserver:s0 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=0

sm7325-common: sepolicy: Resolve qemu_hw_prop denial

avc: denied { read } for name="u:object_r:qemu_hw_prop:s0" dev="tmpfs" ino=1316 scontext=u:r:system_app:s0 tcontext=u:object_r:qemu_hw_prop:s0 tclass=file permissive=0

sm7325-common: sepolicy: Allow system_app to access zram sysfs nodes

avc: denied { search } for name="zram0" dev="sysfs" ino=20744
scontext=u:r:system_app:s0 tcontext=u:object_r:sysfs_zram:s0 tclass=dir
permissive=0

avc: denied { open } for name="mem_used_total" dev="sysfs" ino=20804
scontext=u:r:system_app:s0 tcontext=u:object_r:sysfs_zram:s0 tclass=file
permissive=0

avc: denied { read } for name="mem_used_total" dev="sysfs" ino=20804
scontext=u:r:system_app:s0 tcontext=u:object_r:sysfs_zram:s0 tclass=file
permissive=0

Change-Id: I3c7c337a6ad9a09f2b33d02f0ed6f206db18b855

sm7325-common: sepolicy: Allow system_app to read /proc/pagetypeinfo

avc: denied { read } for name="pagetypeinfo" dev="proc" ino=4026543033
scontext=u:r:system_app:s0 tcontext=u:object_r:proc_pagetypeinfo:s0
tclass=file permissive=0

Change-Id: I16465eb9acca9ff64a755d47f86f4ff424ebe4de

sm7325-common: sepolicy: Allow system_app to read aware available prop

* W libc    : Access denied finding property "ro.vendor.aware_available"

Bug: 130657460
Bug: 144425817
Test: Verify that system_app is able to read the property

sm7325-common: sepolicy: Address `Google Battery HAL' denial

- SELinux : avc:  denied  { find } for interface=vendor.google.google_battery::IGoogleBattery sid=u:r:platform_app:s0:c512,c768 pid=2042 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager permissive=0

sm7325-common: squashed sepolicy updates

sm7325-common: sepolicy: Do not audit linkerconfig

* I auditd  : type=1400 audit(0.0:4): avc: denied { kill } for comm="linkerconfig" capability=5 scontext=u:r:linkerconfig:s0 tcontext=u:r:linkerconfig:s0 tclass=capability permissive=0

Signed-off-by: iusmac <iusico.maxim@libero.it>

sm7325-common: sepolicy: Silence avc denial

* vdc : type=1400 audit(0.0:51): avc: denied { kill } for capability=5 scontext=u:r:vdc:s0 tcontext=u:r:vdc:s0 tclass=capability permissive=0

sm7325-common: sepolicy: Allow fsck to self kill capability

Signed-off-by: Hemant Sachdeva <hemant.evolver@gmail.com>

sm7325-common: sepolicy: Allow odrefresh to kill

* [    6.349136] type=1400 audit(9645771.595:5): avc: denied { kill } for comm=odrefresh capability=5 scontext=u:r:odrefresh:s0 tcontext=u:r:odrefresh:s0 tclass=capability permissive=0

Change-Id: Id24f51e8570dcb32a6b35c57c8f4b6c2be626673

sm7325-common: sepolicy: Address denial for system_suspend

* 04-01 02:04:40.842   745   745 W binder:745_2: type=1400 audit(0.0:19): avc: denied { read } for name="wakeup13" dev="sysfs" ino=61623 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs_rtc:s0 tclass=dir permissive=0

Signed-off-by: AmolAmrit <amol.amrit03@outlook.com>

sm7325-common: sepolicy: Adress more wakeup nodes

Signed-off-by: kleidione <kleidione@gmail.com>

sm7325-common: sepolicy: Address denial for mkswap

* 04-01 02:04:46.390  2852  2852 W mkswap  : type=1400 audit(0.0:29): avc: denied { kill } for capability=5 scontext=u:r:toolbox:s0 tcontext=u:r:toolbox:s0 tclass=capability permissive=0

sm7325-common: sepolicy: Address proc watermark denial

* avc: denied { write } for comm="sh" name="watermark_boost_factor" dev="proc" ino=11632 scontext=u:r:vendor_qti_init_shell:s0 tcontext=u:object_r:proc_watermark_boost_factor:s0 tclass=file permissive=0
 * avc: denied { write } for name="watermark_scale_factor" dev="proc" ino=50754 scontext=u:r:vendor_qti_init_shell:s0 tcontext=u:object_r:proc_watermark_scale_factor:s0 tclass=file permissive=0

sm7325-common: sepolicy: Resolve kernel to search vendor file denials

* 04-01 03:59:04.842    66    66 W kworker/u16:1: type=1400 audit(0.0:12): avc: denied { search } for name="vendor" dev="tmpfs" ino=25704 scontext=u:r:kernel:s0 tcontext=u:object_r:mnt_vendor_file:s0 tclass=dir permissive=0

dubai: sepolicy: Address thermal HAL denial

Signed-off-by: B4579 <B4579@protonmail.com>

dubai: sepolicy: Label more graphics nodes

E WiredAccessoryManager: file /sys/devices/platform/soc/soc:qcom,msm-ext-disp/extcon/extcon3/name not found

E WiredAccessoryManager: file /sys/devices/platform/soc/soc:qcom,msm-ext-disp/extcon/extcon2/name not found

Signed-off-by: B4579 <B4579@protonmail.com>

dubai: sepolicy: allow isolated_app to getattr app_data_file dir

avc: denied { setattr } for name="model-info.pb" dev="dm-5" ino=8358 scontext=u:r:isolated_app:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c20,c257,c512,c768 tclass=file permissive=0
avc: denied { setattr } for name="model.tflite" dev="dm-5" ino=8365 scontext=u:r:isolated_app:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c20,c257,c512,c768 tclass=file permissive=0

Signed-off-by: B4579 <B4579@protonmail.com>

sm7325-common: sepolicy: Allow rild read mnt_vendor_file dir

Change-Id: I099d1ea9e0c690af7e96764852b2122ac8bf6ae9

sm7325-common: sepolicy: Resolve vendor_init_touch denials

Change-Id: Ia71c46662f12f3939e1a4d51b4ab06101f8cc9b7

sm7325-common: sepolicy: Address sensor related denials

Change-Id: I95ef3860e23bb6726e71227aad8999c1d204807d

sm7325-common: sepolicy: Fix avc denials related to linkerconfig

avc: denied { kill } for comm="linkerconfig" capability=5
scontext=u:r:linkerconfig:s0 tcontext=u:r:linkerconfig:s0
tclass=capability permissive=0

Update genfs_contexts